# Worflow example
name: Rubocop
on:
  pull_request:
    branches: [ master ]

jobs:
  rubocop-test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Install Rubocop gem
      run: gem install rubocop
    - name: Run Rubocop
      run: bundle exec rubocop
