# Worflow example
name: CI
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Rubocop checks
      uses: andrewmcodes-archive/rubocop-linter-action@v3.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
